name: Tests

on:
  push:
    branches: [ fix_numba ]

jobs:


  Numba:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Cache pip
        uses: actions/cache@v2
        env:
          cache-name: cache-pip
        with:
          path: ~/.local
          key: ${{runner.os }}-build-${{ env.cache-name }}
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Make with numba
        run: |
          make ACC=numba numba
      - name: Unit tests
        uses: ./.github/actions/pytest_run
